### ISSUE TITLE
Make the output elegant

### ISSUE THREAD

**Issue by orta** [f-meloni/Rocket#13]
A great example from releasing Danger JS:

<img width="1906" alt="screen shot 2018-12-26 at 7 40 52 am" src="https://user-images.githubusercontent.com/49038/50446629-fd31ab80-08e3-11e9-94c0-9451082fc90b.png">

<img width="723" alt="screen shot 2018-12-26 at 7 42 21 am" src="https://user-images.githubusercontent.com/49038/50446631-fe62d880-08e3-11e9-8125-8d3bf6b22d22.png">

**Comment by orta** [comment]
( I don't except the spinners :) )

**Comment by f-meloni** [comment]
cool, will have a think on how do it :)
But shouldn't be a problem at all
