### ISSUE TITLE
Output steps as they happen

### ISSUE THREAD

**Issue by orta** [f-meloni/Rocket#8]
<img width="968" alt="screen shot 2018-12-19 at 2 07 00 pm" src="https://user-images.githubusercontent.com/49038/50225082-70449a80-0397-11e9-8adf-9dd9e4c08667.png">

Ideally it'd be nice to know what steps are being ran 👍

**Comment by f-meloni** [comment]
Yep, i will have a look at that, thanks :)

**Comment by f-meloni** [comment]
<img width="1671" alt="schermata 2018-12-23 alle 16 07 06" src="https://user-images.githubusercontent.com/17830956/50385390-d77e8980-06cc-11e9-87d2-e48202017dbe.png">

I have it working, just have to tweak it a little bit :)

**Comment by f-meloni** [comment]
Fixed :)
